# Generated by Django 3.2.6 on 2021-09-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyMaterials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(upload_to='studyMaterials/media'),
        ),
    ]
