# Generated by Django 3.2.6 on 2021-09-05 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyMaterials', '0002_auto_20210905_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='date',
        ),
    ]
