# Generated by Django 3.2.6 on 2021-09-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='normal_exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='none', max_length=200)),
                ('a', models.CharField(default='none', max_length=50)),
                ('b', models.CharField(default='none', max_length=50)),
                ('c', models.CharField(default='none', max_length=50)),
                ('d', models.CharField(default='none', max_length=50)),
                ('currect_ans', models.CharField(default='none', max_length=50)),
            ],
        ),
    ]
